from __future__ import annotations

from .admin import (
    AdminAPI,
    AdminModule,
    BillingModule,
    KnowledgeModule,
    MCPModule,
    MemoryModule,
    ModelsModule,
    OrganizationsModule,
    PluginsModule,
    TenantsModule,
    UsersModule,
)
from .analytics import AnalyticsService
from .audit import AuditService
from .config import AdminConfig
from .diagnostics import DiagnosticsService
from .exceptions import (
    AdminError,
    AlertNotFoundError,
    AnalyticsUnavailableError,
    AuditQueryError,
    ComponentUnavailableError,
    ConfigurationError,
    DashboardError,
    FeatureFlagInvalidError,
    FeatureFlagNotFoundError,
    HealthCheckFailedError,
    MaintenanceActiveError,
    ModuleNotFoundError,
    MonitorError,
    SettingNotFoundError,
    SettingValidationError,
)
from .feature_flags import FeatureFlagManager
from .health import (
    AuthHealthCheck,
    BillingHealthCheck,
    CallableHealthCheck,
    GatewayHealthCheck,
    HealthCheck,
    HealthCheckRegistry,
    KnowledgeHealthCheck,
    MCPHealthCheck,
    MemoryHealthCheck,
    ModelsHealthCheck,
    OrganizationsHealthCheck,
    PluginsHealthCheck,
    RateLimiterHealthCheck,
    StorageHealthCheck,
    TenancyHealthCheck,
    create_default_registry,
)
from .logging import AdminLogger
from .maintenance import MaintenanceManager
from .metrics import AdminMetricsTracker
from .models import (
    AdminEventType,
    AlertRecord,
    AlertSeverity,
    AlertStatus,
    AnalyticsPoint,
    AuditRecord,
    ComponentHealth,
    ComponentName,
    DashboardReport,
    DiagnosticsReport,
    FeatureFlag,
    HealthStatus,
    MaintenanceStatus,
    SettingDefinition,
    SettingType,
    SystemStatus,
    generate_id,
)
from .monitoring import (
    AlertmanagerBackend,
    LokiBackend,
    MonitoringBackend,
    MonitoringService,
    OpenTelemetryBackend,
    PrometheusBackend,
)
from .operations import OperationsService
from .repositories import (
    AdminRepositories,
    AlertRepository,
    AuditRepository,
    DEFAULT_SETTINGS,
    FlagRepository,
    InMemoryAlertRepository,
    InMemoryAuditRepository,
    InMemoryFlagRepository,
    InMemorySettingsRepository,
    SettingsRepository,
)
from .settings import SystemSettingsManager
from .statistics import StatisticsService

__all__ = [
    "AdminAPI",
    "AdminConfig",
    "AdminError",
    "AdminEventType",
    "AdminLogger",
    "AdminMetricsTracker",
    "AdminModule",
    "AdminRepositories",
    "AlertNotFoundError",
    "AlertRecord",
    "AlertRepository",
    "AlertSeverity",
    "AlertStatus",
    "AlertmanagerBackend",
    "AnalyticsPoint",
    "AnalyticsService",
    "AnalyticsUnavailableError",
    "AuditQueryError",
    "AuditRecord",
    "AuditRepository",
    "AuditService",
    "AuthHealthCheck",
    "BillingHealthCheck",
    "BillingModule",
    "CallableHealthCheck",
    "ComponentHealth",
    "ComponentName",
    "ComponentUnavailableError",
    "ConfigurationError",
    "DEFAULT_SETTINGS",
    "DashboardError",
    "DashboardReport",
    "DiagnosticsReport",
    "DiagnosticsService",
    "FeatureFlag",
    "FeatureFlagInvalidError",
    "FeatureFlagManager",
    "FeatureFlagNotFoundError",
    "FlagRepository",
    "GatewayHealthCheck",
    "HealthCheck",
    "HealthCheckFailedError",
    "HealthCheckRegistry",
    "HealthStatus",
    "InMemoryAlertRepository",
    "InMemoryAuditRepository",
    "InMemoryFlagRepository",
    "InMemorySettingsRepository",
    "KnowledgeHealthCheck",
    "KnowledgeModule",
    "LokiBackend",
    "MCPHealthCheck",
    "MCPModule",
    "MaintenanceActiveError",
    "MaintenanceManager",
    "MaintenanceStatus",
    "MemoryHealthCheck",
    "MemoryModule",
    "ModelsHealthCheck",
    "ModelsModule",
    "MonitorError",
    "MonitoringBackend",
    "MonitoringService",
    "ModuleNotFoundError",
    "OpenTelemetryBackend",
    "OperationsService",
    "OrganizationsHealthCheck",
    "OrganizationsModule",
    "PluginsHealthCheck",
    "PluginsModule",
    "PrometheusBackend",
    "RateLimiterHealthCheck",
    "SettingDefinition",
    "SettingNotFoundError",
    "SettingType",
    "SettingValidationError",
    "SettingsRepository",
    "StatisticsService",
    "StorageHealthCheck",
    "SystemStatus",
    "TenancyHealthCheck",
    "TenantsModule",
    "UsersModule",
    "create_admin_api",
    "create_default_registry",
    "generate_id",
]


def create_admin_api(
    config: AdminConfig | None = None,
    logger: AdminLogger | None = None,
    metrics: AdminMetricsTracker | None = None,
    flags: FeatureFlagManager | None = None,
    settings: SystemSettingsManager | None = None,
    maintenance: MaintenanceManager | None = None,
    health: HealthCheckRegistry | None = None,
    analytics: AnalyticsService | None = None,
    statistics: StatisticsService | None = None,
    monitoring: MonitoringService | None = None,
    diagnostics: DiagnosticsService | None = None,
    audit: AuditService | None = None,
    operations: OperationsService | None = None,
    tenants: TenantsModule | None = None,
    organizations: OrganizationsModule | None = None,
    users: UsersModule | None = None,
    billing: BillingModule | None = None,
    models: ModelsModule | None = None,
    knowledge: KnowledgeModule | None = None,
    memory: MemoryModule | None = None,
    mcp: MCPModule | None = None,
    plugins: PluginsModule | None = None,
) -> AdminAPI:
    return AdminAPI(
        config=config,
        logger=logger,
        metrics=metrics,
        flags=flags,
        settings=settings,
        maintenance=maintenance,
        health=health,
        analytics=analytics,
        statistics=statistics,
        monitoring=monitoring,
        diagnostics=diagnostics,
        audit=audit,
        operations=operations,
        tenants=tenants,
        organizations=organizations,
        users=users,
        billing=billing,
        models=models,
        knowledge=knowledge,
        memory=memory,
        mcp=mcp,
        plugins=plugins,
    )
