apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-router
  namespace: argocd
  labels:
    app.kubernetes.io/name: ai-router
    app.kubernetes.io/version: 1.0.0-rc.1
spec:
  project: default
  source:
    repoURL: https://github.com/salmansaidibrohim267-prog/AI-Router
    path: deployment/k8s
    targetRevision: v1.0.0-rc.1
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-router
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
  revisionHistoryLimit: 5
