"""Security & Compliance subsystem (Stage 10.9).

Comprehensive security framework for the AI Router: pluggable secret
management, envelope encryption, key lifecycle management, zero trust policy
enforcement, immutable audit logging, privacy controls, compliance reporting,
threat detection and SIEM monitoring.
"""

from .audit import AuditRepository, AuditService, create_audit_service
from .compliance import ComplianceManager, create_compliance_manager
from .config import SecurityConfig
from .crypto import AESCipher, EncryptionService, FieldCipher, StorageEncryption, create_encryption_service
from .exceptions import (
    AuditError,
    AuditIntegrityError,
    AuthenticationError,
    AuthorizationError,
    ComplianceError,
    DataSubjectRequestError,
    DecryptionError,
    EncryptionError,
    IncidentError,
    KeyExpiredError,
    KeyManagementError,
    KeyRevokedError,
    KeyVersionError,
    MonitoringError,
    PolicyError,
    PolicyEvaluationError,
    PrivacyError,
    SecretBackendError,
    SecretError,
    SecretNotFoundError,
    SecurityError,
    SessionValidationError,
    TenantValidationError,
    ThreatError,
)
from .keys import HSMAdapter, KeyManager, KMSAdapter, SimulatedHSMAdapter, create_key_manager
from .logging import SecurityLogger
from .manager import SecurityManager, create_security_manager
from .metrics import SecurityMetricsTracker
from .models import (
    AuditEventType,
    AuditRecord,
    AuditSeverity,
    AuthContext,
    AuthMethod,
    ComplianceFramework,
    ComplianceReport,
    Control,
    ControlStatus,
    DataSubjectRequest,
    DataSubjectRequestStatus,
    DataSubjectRequestType,
    Decision,
    EncryptionAlgorithm,
    EncryptionKey,
    Envelope,
    Finding,
    Incident,
    IncidentStatus,
    KeyPurpose,
    KeyStatus,
    PIIField,
    PIIKind,
    Policy,
    PolicyEffect,
    PolicyResult,
    Secret,
    SecretKind,
    SecretStatus,
    SecurityAlert,
    Session,
    SessionStatus,
    Subject,
    ThreatEvent,
    ThreatSeverity,
    ThreatType,
    generate_id,
)
from .monitoring import (
    DatadogSink,
    ElasticSink,
    MonitoringService,
    SiemRegistry,
    SiemSink,
    SplunkSink,
    StdoutSink,
    create_monitoring_service,
)
from .privacy import PIIDetector, PrivacyService, create_privacy_service
from .secrets import (
    AWSSecretsBackend,
    AzureBackend,
    EnvironmentBackend,
    GoogleBackend,
    KubernetesBackend,
    SecretBackend,
    SecretBackendRegistry,
    SecretManager,
    VaultBackend,
    create_secret_backend,
    create_secret_manager,
)
from .threat import IncidentManager, ThreatDetector, create_incident_manager, create_threat_detector
from .zero_trust import ZeroTrustEnforcer, create_zero_trust_enforcer

__all__ = [
    "SecurityConfig",
    "SecurityLogger",
    "SecurityMetricsTracker",
    "SecurityManager",
    "create_security_manager",
    "SecretManager",
    "SecretBackend",
    "SecretBackendRegistry",
    "EnvironmentBackend",
    "VaultBackend",
    "KubernetesBackend",
    "AWSSecretsBackend",
    "AzureBackend",
    "GoogleBackend",
    "create_secret_backend",
    "create_secret_manager",
    "AESCipher",
    "EncryptionService",
    "FieldCipher",
    "StorageEncryption",
    "create_encryption_service",
    "HSMAdapter",
    "SimulatedHSMAdapter",
    "KMSAdapter",
    "KeyManager",
    "create_key_manager",
    "ZeroTrustEnforcer",
    "create_zero_trust_enforcer",
    "AuditRepository",
    "AuditService",
    "create_audit_service",
    "PIIDetector",
    "PrivacyService",
    "create_privacy_service",
    "ComplianceManager",
    "create_compliance_manager",
    "ThreatDetector",
    "IncidentManager",
    "create_threat_detector",
    "create_incident_manager",
    "SiemSink",
    "StdoutSink",
    "SplunkSink",
    "ElasticSink",
    "DatadogSink",
    "SiemRegistry",
    "MonitoringService",
    "create_monitoring_service",
    # exceptions
    "SecurityError",
    "SecretError",
    "SecretNotFoundError",
    "SecretBackendError",
    "EncryptionError",
    "DecryptionError",
    "KeyManagementError",
    "KeyRevokedError",
    "KeyExpiredError",
    "KeyVersionError",
    "PolicyError",
    "AuthenticationError",
    "AuthorizationError",
    "TenantValidationError",
    "SessionValidationError",
    "PolicyEvaluationError",
    "AuditError",
    "AuditIntegrityError",
    "PrivacyError",
    "DataSubjectRequestError",
    "ComplianceError",
    "ThreatError",
    "IncidentError",
    "MonitoringError",
    # models
    "Secret",
    "SecretKind",
    "SecretStatus",
    "EncryptionAlgorithm",
    "EncryptionKey",
    "Envelope",
    "KeyPurpose",
    "KeyStatus",
    "AuthContext",
    "AuthMethod",
    "Subject",
    "Session",
    "SessionStatus",
    "Decision",
    "Policy",
    "PolicyEffect",
    "PolicyResult",
    "AuditRecord",
    "AuditEventType",
    "AuditSeverity",
    "PIIField",
    "PIIKind",
    "DataSubjectRequest",
    "DataSubjectRequestType",
    "DataSubjectRequestStatus",
    "ComplianceFramework",
    "ComplianceReport",
    "Control",
    "ControlStatus",
    "Finding",
    "ThreatEvent",
    "ThreatType",
    "ThreatSeverity",
    "Incident",
    "IncidentStatus",
    "SecurityAlert",
    "generate_id",
]
